# Generated by Django 6.0.6 on 2026-06-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='confederation',
            field=models.CharField(blank=True, choices=[('CONMEBOL', 'CONMEBOL'), ('UEFA', 'UEFA'), ('CAF', 'CAF'), ('AFC', 'AFC'), ('OFC', 'OFC'), ('CONCACAF', 'CONCACAF')], max_length=10),
        ),
    ]
