# Generated by Django 6.0.6 on 2026-06-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_team_confederation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
