# Generated by Django 6.0.6 on 2026-06-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_stadium_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='phase',
            field=models.CharField(choices=[('grupo', 'Fase de Grupos'), ('trinta_dois_avos', '32-avos de Final'), ('oitavas', 'Oitavas de Final'), ('quartas', 'Quartas de Final'), ('semi', 'Semifinal'), ('terceiro_lugar', 'Terceiro Lugar'), ('final', 'Final')], max_length=20),
        ),
    ]
