# Generated by Django 6.0.6 on 2026-06-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_round_end_date_round_start_date_alter_round_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='penalties_away',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='penalties_home',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
