# Generated by Django 6.0.6 on 2026-06-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_external_id_match_penalties_away_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
