# Generated by Django 6.0.6 on 2026-06-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_team_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='elapsed_minute',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
