"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load variables from a local .env file (if present) into os.environ so
# settings below can rely on os.getenv(...). We use a tiny stdlib-only
# parser to avoid pulling python-decouple / python-dotenv as a dependency.
_ENV_PATH = BASE_DIR / '.env'
if _ENV_PATH.exists():
    for _line in _ENV_PATH.read_text(encoding='utf-8').splitlines():
        _line = _line.strip()
        if not _line or _line.startswith('#') or '=' not in _line:
            continue
        _key, _, _value = _line.partition('=')
        os.environ.setdefault(_key.strip(), _value.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@lg85o*4j1&-!x^wabxm4hux$2ro)35(fl+45f^nnw7z79tsf&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'pools',
    'matches',
    'predictions',
    'rankings',
    'live',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'users.CustomUser'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'bolao@bolao copa.com'

# API-Football v3 (free tier, 100 req/day)
API_FOOTBALL_KEY = os.getenv('API-FOOTBALL-KEY', '')
API_FOOTBALL_BASE_URL = os.getenv(
    'API-FOOTBALL-BASE-URL',
    'https://v3.football.api-sports.io',
)
API_FOOTBALL_LEAGUE_ID = int(os.getenv('API-FOOTBALL-LEAGUE-ID', '1'))
API_FOOTBALL_SEASON = int(os.getenv('API-FOOTBALL-SEASON', '2026'))
API_FOOTBALL_TIMEOUT = int(os.getenv('API-FOOTBALL-TIMEOUT', '15'))

# football-data.org v4 (free tier, 10 req/min).
# The 2026 FIFA World Cup is officially covered by this API on the free
# plan; its competition id is 2000 (discovered via /competitions).
FOOTBALL_DATA_ORG_KEY = os.getenv('FOOTBALL-DATA-ORG-KEY', '')
FOOTBALL_DATA_ORG_BASE_URL = os.getenv(
    'FOOTBALL-DATA-ORG-BASE-URL',
    'https://api.football-data.org/v4',
)
FOOTBALL_DATA_ORG_WORLD_CUP_ID = int(
    os.getenv('FOOTBALL-DATA-ORG-WORLD-CUP-ID', '2000'),
)
FOOTBALL_DATA_ORG_TIMEOUT = int(
    os.getenv('FOOTBALL-DATA-ORG-TIMEOUT', '15'),
)
