# Generated by Django 6.0.6 on 2026-06-09 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0007_match_elapsed_minute'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('goal', 'Gol'), ('yellow_card', 'Cartao amarelo'), ('red_card', 'Cartao vermelho'), ('substitution_in', 'Substituicao - entrou'), ('substitution_out', 'Substituicao - saiu')], max_length=20)),
                ('player', models.CharField(max_length=200)),
                ('assist_player', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_events', to='matches.team')),
            ],
            options={
                'ordering': ('minute', 'id'),
                'indexes': [models.Index(fields=['match', 'minute', 'type', 'player'], name='me_match_min_type_player_idx')],
            },
        ),
    ]
